### ISSUE TITLE
import claims no module named xenaAPI

### ISSUE THREAD

**Issue by lisabang** [ucscXena/xenaPython#2]
I have installed xenaPython before successfully on my mac, but when trying to install on our redhat server, the install finished but the first attempt at import claims that there is no module named xenaAPI.

`In [2]: import xenaPython
ImportError                               Traceback (most recent call last)
<ipython-input-2-18063d206c24> in <module>()
----> 1 import xenaPython

/ssfff/Anaconda-3.4.2.0/lib/python3.5/site-packages/xenaPython/__init__.py in <module>()
----> 1 import xenaAPI
      2 import xenaQuery

ImportError: No module named 'xenaAPI'`

**Comment by acthp** [comment]
My first guess is something to do with python 3. Try python 2 if you can. We'll look at the python 3 install.

**Comment by lisabang** [comment]
python 2 install works great with xena.  Thanks!
